global:
  scrape_interval: 15s # How often Prometheus scrapes targets (15 seconds in this example)
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:8085','127.0.0.1:8085','3.88.210.223:8085'] # Replace 'nodejs-app' with your Node.js service name and port
