name: Docker CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/api:${{github.run_number}}
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
     
          
    

      - name: Deploy to EC2 instances
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop api || true
            docker rm api || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/api:${{github.run_number}}
            docker run -d --name api -p 8085:8085 ${{ secrets.DOCKER_USERNAME }}/api:${{github.run_number}}








            